# Generated by Django 5.2.4 on 2025-07-13 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('bobot', models.FloatField()),
                ('sifat', models.CharField(choices=[('benefit', 'Benefit'), ('cost', 'Cost')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_selector.alternatif')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_selector.kriteria')),
            ],
            options={
                'unique_together': {('alternatif', 'kriteria')},
            },
        ),
    ]
